### ISSUE TITLE
Update birth occurrences

### ISSUE THREAD

**Issue by ejwillemse** [ejwillemse/sim-demog-NUK-open#1]
Allow births to occur "naturally" after the burn-period using the fertility rates, instead of a death automatically triggering a birth.

**Comment by wcchin** [comment]
Done by modifying individual.py, pop_hh.py and simulation.py.
The model is tested and run "normally". 
But we have to find some ways to explore and examine if the result is "correct".

**Comment by ejwillemse** [comment]
@wcchin great stuff. We can look at and discuss the results tomorrow after the NSE meeting.
